### ISSUE TITLE
发布博文的code显示问题

### ISSUE THREAD

**Issue by dufeisolo** [xtg20121013/blog_xtg#1]
当在发布的博文中，代码中如果使用了```code```的方式编写代码，当行是没有问题的，但是多行代码就会又问题，不知是否是markdown模块的解析问题

**Comment by xtg20121013** [comment]
以后遇到这个问题的同学，参考： [https://github.com/xtg20121013/blog_xtg/pull/2](https://github.com/xtg20121013/blog_xtg/pull/2)
